import type { Customer } from "./customers.types";

export const CUSTOMERS: Customer[] = [
  {
    id: "c1",
    fullName: "John Kamau",
    phone: "0712 111 222",
    email: "john.kamau@gmail.com",
    location: "Westlands",
    contactPreference: "Whatsapp",
    optedInToPromos: true,
    memberSince: "2023-02-10",
    vehicles: [
      {
        id: "v1",
        plate: "KDA 123A",
        make: "Toyota",
        model: "Prado",
        variant: "J150",
        year: 2019,
        color: "Silver",
      },
    ],
    totalVisits: 12,
    lastVisit: "2026-06-01",
    totalSpent: 87000,
    loyaltyPoints: 870,
    offersHistory: [
      {
        id: "o1",
        dateSent: "2026-05-01",
        title: "VIP Exclusive",
        type: "Discount %",
        channel: "Whatsapp",
        status: "Redeemed",
      },
    ],
    customerNotes: [
      {
        id: "n1",
        date: "2026-04-10",
        text: "Prefers Pioneer head units",
        addedBy: "Kevin",
        pinned: true,
      },
    ],
  },
  {
    id: "c2",
    fullName: "Sarah Wanjiru",
    phone: "0723 222 333",
    email: "sarah.w@yahoo.com",
    location: "Karen",
    contactPreference: "Whatsapp",
    optedInToPromos: true,
    memberSince: "2023-08-15",
    vehicles: [
      {
        id: "v2",
        plate: "KBZ 456B",
        make: "VW",
        model: "Golf",
        variant: "GTI",
        year: 2020,
        color: "White",
      },
    ],
    totalVisits: 7,
    lastVisit: "2026-05-20",
    totalSpent: 54000,
    loyaltyPoints: 540,
    offersHistory: [],
    customerNotes: [
      {
        id: "n2",
        date: "2026-03-05",
        text: "Very particular about clean cable routing",
        addedBy: "Brian",
        pinned: false,
      },
    ],
  },
  {
    id: "c3",
    fullName: "David Otieno",
    phone: "0734 333 444",
    location: "Thika Road",
    contactPreference: "Call",
    optedInToPromos: false,
    memberSince: "2024-01-20",
    vehicles: [
      {
        id: "v3",
        plate: "KCC 789C",
        make: "Toyota",
        model: "Fielder",
        variant: "NZE",
        year: 2018,
      },
      {
        id: "v4",
        plate: "KDE 012D",
        make: "Nissan",
        model: "X-Trail",
        variant: "T32",
        year: 2021,
      },
    ],
    totalVisits: 4,
    lastVisit: "2026-04-15",
    totalSpent: 28000,
    loyaltyPoints: 280,
    offersHistory: [],
    customerNotes: [],
  },
  {
    id: "c4",
    fullName: "Amina Hassan",
    phone: "0745 444 555",
    location: "South B",
    contactPreference: "SMS",
    optedInToPromos: true,
    memberSince: "2025-01-05",
    vehicles: [
      {
        id: "v5",
        plate: "KEF 345E",
        make: "Mazda",
        model: "Demio",
        variant: "DE3FS",
        year: 2017,
        color: "Red",
      },
    ],
    totalVisits: 2,
    lastVisit: "2026-03-10",
    totalSpent: 12000,
    loyaltyPoints: 120,
    offersHistory: [],
    customerNotes: [],
  },
  {
    id: "c5",
    fullName: "Peter Njoroge",
    phone: "0756 555 666",
    email: "peter.njoroge@business.co.ke",
    location: "Kilimani",
    birthday: "1985-06-08",
    contactPreference: "Whatsapp",
    optedInToPromos: true,
    memberSince: "2022-11-01",
    vehicles: [
      {
        id: "v6",
        plate: "KFG 678F",
        make: "BMW",
        model: "X3",
        variant: "xDrive20d",
        year: 2022,
        color: "Black",
      },
    ],
    totalVisits: 15,
    lastVisit: "2026-06-04",
    totalSpent: 145000,
    loyaltyPoints: 1450,
    offersHistory: [
      {
        id: "o2",
        dateSent: "2026-06-01",
        title: "Birthday Special",
        type: "Birthday Offer",
        channel: "Whatsapp",
        status: "Sent",
      },
    ],
    customerNotes: [
      {
        id: "n3",
        date: "2026-01-15",
        text: "Referred 3 friends to the shop",
        addedBy: "Mercy",
        pinned: true,
      },
    ],
  },
  {
    id: "c6",
    fullName: "Grace Muthoni",
    phone: "0767 666 777",
    location: "Ngong Road",
    contactPreference: "Call",
    optedInToPromos: true,
    memberSince: "2026-05-12",
    vehicles: [
      {
        id: "v7",
        plate: "KGH 901G",
        make: "Toyota",
        model: "Axio",
        variant: "NZE141",
        year: 2016,
      },
    ],
    totalVisits: 1,
    lastVisit: "2026-05-12",
    totalSpent: 8500,
    loyaltyPoints: 85,
    offersHistory: [],
    customerNotes: [],
  },
  {
    id: "c7",
    fullName: "Michael Odhiambo",
    phone: "0778 777 888",
    email: "m.odhiambo@gmail.com",
    location: "Mombasa Road",
    contactPreference: "Whatsapp",
    optedInToPromos: true,
    memberSince: "2023-04-22",
    vehicles: [
      {
        id: "v8",
        plate: "KHI 234H",
        make: "Subaru",
        model: "Forester",
        variant: "SH5",
        year: 2019,
        color: "Blue",
      },
    ],
    totalVisits: 8,
    lastVisit: "2026-05-28",
    totalSpent: 67000,
    loyaltyPoints: 670,
    offersHistory: [],
    customerNotes: [
      {
        id: "n4",
        date: "2025-12-01",
        text: "Loves JL Audio subwoofers — brand loyal",
        addedBy: "James",
        pinned: false,
      },
    ],
  },
  {
    id: "c8",
    fullName: "Fatuma Ali",
    phone: "0789 888 999",
    location: "Eastleigh",
    contactPreference: "Whatsapp",
    optedInToPromos: true,
    memberSince: "2025-03-18",
    vehicles: [
      {
        id: "v9",
        plate: "KIJ 567I",
        make: "Toyota",
        model: "Vitz",
        variant: "KSP90",
        year: 2015,
      },
    ],
    totalVisits: 3,
    lastVisit: "2026-02-20",
    totalSpent: 18000,
    loyaltyPoints: 180,
    offersHistory: [],
    customerNotes: [],
  },
  {
    id: "c9",
    fullName: "James Kariuki",
    phone: "0790 999 000",
    location: "South C",
    contactPreference: "Call",
    optedInToPromos: false,
    memberSince: "2023-10-05",
    vehicles: [
      {
        id: "v10",
        plate: "KJK 890J",
        make: "Toyota",
        model: "Hilux",
        variant: "GD6",
        year: 2020,
        color: "White",
      },
    ],
    totalVisits: 6,
    lastVisit: "2026-05-10",
    totalSpent: 48000,
    loyaltyPoints: 480,
    offersHistory: [],
    customerNotes: [],
  },
  {
    id: "c10",
    fullName: "Linda Chebet",
    phone: "0701 000 111",
    location: "Langata",
    contactPreference: "SMS",
    optedInToPromos: true,
    memberSince: "2025-09-30",
    vehicles: [
      {
        id: "v11",
        plate: "KKL 123K",
        make: "Hyundai",
        model: "Tucson",
        variant: "TLE",
        year: 2021,
      },
    ],
    totalVisits: 1,
    lastVisit: "2025-09-30",
    totalSpent: 6000,
    loyaltyPoints: 60,
    offersHistory: [],
    customerNotes: [],
  },
  {
    id: "c11",
    fullName: "Hassan Mwenda",
    phone: "0712 111 333",
    email: "hassan.mwenda@enterprise.co.ke",
    location: "CBD",
    contactPreference: "Whatsapp",
    optedInToPromos: true,
    memberSince: "2022-03-14",
    vehicles: [
      {
        id: "v12",
        plate: "KLM 456L",
        make: "Toyota",
        model: "Land Cruiser",
        variant: "VX",
        year: 2018,
        color: "Black",
      },
    ],
    totalVisits: 20,
    lastVisit: "2026-06-03",
    totalSpent: 230000,
    loyaltyPoints: 2300,
    offersHistory: [
      {
        id: "o3",
        dateSent: "2026-04-01",
        title: "Q2 VIP Reward",
        type: "Loyalty Reward",
        channel: "Whatsapp",
        status: "Redeemed",
      },
    ],
    customerNotes: [
      {
        id: "n5",
        date: "2026-02-20",
        text: "Fleet account — manages 3 vehicles for company",
        addedBy: "Peter",
        pinned: true,
      },
    ],
  },
  {
    id: "c12",
    fullName: "Ruth Wangari",
    phone: "0723 222 444",
    email: "ruth.w@gmail.com",
    location: "Westlands",
    birthday: "1993-06-22",
    contactPreference: "Whatsapp",
    optedInToPromos: true,
    memberSince: "2024-02-08",
    vehicles: [
      {
        id: "v13",
        plate: "KMN 789M",
        make: "VW",
        model: "Polo Vivo",
        variant: "GP",
        year: 2019,
        color: "Silver",
      },
    ],
    totalVisits: 5,
    lastVisit: "2026-04-25",
    totalSpent: 32000,
    loyaltyPoints: 320,
    offersHistory: [],
    customerNotes: [],
  },
];
